### ISSUE TITLE
Document threshold reasoning in clean_data function

### ISSUE THREAD

**Issue by goatsweater** [canmet-energy/btap_ml#15]
The clean data function has hard coded threshold values of 50% not NA values and greater than 3 unique values in a column, but it isn't clear why those thresholds were chosen. How those values were reached should be documented.

This may not warrant a full explanation in the documentation. Maybe just code comments so people know the impact of making changes. If a longer explanation is required then maybe a spot in the docs is warranted.

**Comment by maybuksho** [comment]
The 50% threshold is a way to eliminate columns with too much missing values in the dataset. I wont really call it hardcoding. We cant use N/A as it will elimnate the entire row /datapoint_id. Giving the number of features we have to work it its better we eliminate columns with features that have too much missing values than to eliminate by rows, which is what N/A will do . 

For columns with low values less than 3, i decided to drop them , however, even if I do no drop them during data cleaning they would eventually be dropped during feature engineering, since these features will have low variance and hence have little or no significant contribution to the accuracy of the model .  

Since I know such features wont be of so much use, i decided to eliminate them during data cleaning, to avoid having too much redundant data we are working with during preprocessing. So the choice of dropping columns with less than 3 unique features is just an intuition based on the rationale discussed above.
