### ISSUE TITLE
Regenerate the dataset

### ISSUE THREAD

**Issue by maybuksho** [canmet-energy/btap_ml#8]
@ckirney 
I observed that the dataset you recently sent (5000 datapoint_id), all the values in the net_site_eui_gj_per_m_sq column EU are ALL positive. However, in the first set of dataset we got, the values in  columns EU are either  positive and negative. 

Since the dataset with 5000 datapoint_id is larger than the previous one, I used this dataset to train the model. However, since the model built is not trained to learn about the negative energy values, the model is having high error predicting negative values. 

Given whichever scenario is ideal, if in production we do expect the EU columns to have negative values, then I will need you to please rerun the 5000 datapoint simulation so that we have a mix of both positive and negative values in column EU.  Alternatively, if column EU should only be positive, then please help rerun the 1000 datapoint for validation.

**Comment by ckirney** [comment]
Started new run of 6000 simulations on 2021-10-29 with revised openstudio-standards code that properly accounts for solar panels.  Partway through the analysis I noticed that of the roughly 2500 simulations that had run, 260 failed.  I am still investigating the failures.  I also realized that the following parameters had multiple possible values:
ext_floor_cond
ground_roof_cond
glass_door_cond
overhead_door_cond
skylight_cond
glass_door_solar_trans
skylight_solar_trans
srr_set

However, none of the above parameters are applied to the building type used.  The result is that many of the results could be essentially duplicates of one another.  When I sort out the errors I will modify the analysis parameters so that the above parameters only use defaults.

**Comment by ckirney** [comment]
I have also realized that there can still be redundant files even with the adjustments I describe above.  When "primary_heating_fuel" = "Electricity" any files with any combination of the following input parameters will produce the same result:

boiler_eff = 
      "NECB_Default",
      "NECB 85% Efficient Condensing Boiler",
      "NECB 88% Efficient Condensing Boiler",
      "NECB 91% Efficient Condensing Boiler",
      "NECB 94% Efficient Condensing Boiler",
      "Viessmann Vitocrossal 300 CT3-17 96.2% Efficient Condensing Gas Boiler"

furnace_eff =
      "NECB_Default",
      "NECB 85% Efficient Condensing Gas Furnace",
      "NECB 88% Efficient Condensing Gas Furnace",
      "NECB 91% Efficient Condensing Gas Furnace",
      "NECB 94% Efficient Condensing Gas Furnace"

shw_eff =
      "NECB_Default",
      "Natural Gas 85% Efficient SHW",
      "Natural Gas 88% Efficient SHW",
      "Natural Gas Direct Vent with Electric Ignition",
      "Natural Gas Power Vent with Electric Ignition",
      "Natural Gas Power Vent with Electric Ignition 97% Efficient"

I will produce two sets of results to avoid this.  One set with primary_heating_fuel = "NaturalGas" and which includes all of the above parameters.  Another set will have primary_heating_fuel = "Electricity" but the above parameters will all be set to their default values.  @maybuksho, I imagine this may have led (at least partially) to the high accuracy of the model you produced before.

**Comment by maybuksho** [comment]
Thanks Chris for the detailed triage of issues that could affect the quality of the data generated. Definitely, its ideal we are not having duplicate scenarios for each datapoint_id as that would not reveal the true test of the model. I agree that having same duplicates could make the model have the low error we currently have. However, I do not understand how the two sets of results will work. Does it mean you want to send data from each batch in the same file at the end? or will you be merging the data in the two files together? What is important is that the data we want to use for training should have similar data as those we want to use validation i.e. I will expect data used for training to have instances of primary_heating_fuel = "NaturalGas" and instances where primary_heating_fuel = "Electricity".

**Comment by ckirney** [comment]
I am creating the two sets of results as a work around because there is currently no easy way for me to adjust the initial yml file so that all of the outputs are unique.

I will probably merge these two sets of results together and then send them to you that way.  Essentially, they should be treated as one set of results.  You can use part of them for training the model and then another part to test it.  Also, when doing the sampling for training, you should probably make sure that you select results whose "primary_heating_fuel" is "NaturalGas" proportional to the total number of "NaturalGas" results done.  The same with "Electricity".  What I mean by that is that I am trying to run 1000 files where the "primary_heating_fuel" is "Electricity" and 5000 files where the "primary_heating_fuel" is "NaturalGas".  If you were going to choose 1000 results for training, for example (I'm not sure how many you would choose), then you should choose 167 results with "Electricity" (1000/6000 ~= 167) as the "primary_heating_fuel" and 833 results (5000/6000 ~= 833) with "NaturalGas" as the "primary_heating_fuel".

**Comment by srgilani** [comment]
In addition to Chris' list here https://github.com/canmet-energy/btap_ml/issues/8#issuecomment-956303495, the below ECMs are also redundant for the FullServiceRestaurant archetype in Montreal as they do not have any impact on the energy use of this archetype in this climate zone:

- daylighting_type
- chiller_type
- dcv_type (only the "No_DCV" input as it gives the same result as the "NECB_Default" input)

Note that the redundant arguments/inputs for each building type and climate zone may differ. Hence, it is important to check them for future analysis of other building types and climate zones.

**Comment by ckirney** [comment]
@maybuksho, I have finished re-running the analysis and have taken care to avoid creating redundant datapoints.  I uploaded the results to nrcan-btap/input_data in MinIO.  The files are as follows:
sample-lhs_statcan_gas_2021-11-05.yml:  Input parameters used for the analysis of buildings primarily using gas heating
output_gas_2021-11-05.xlsx:  Annual results for the buildings primarily using gas heating
total_hourly_res_gas_2021-11-05.csv:  Hourly results for the buildings primarily using gas heating
sample-lhs_statcan_elec_2021-11-05.yml:  Input parameters used for the analysis of buildings primarily using electric heating
output_elec_2021-11-05.xlsx:  Annual results for the buildings primarily using electric heating
total_hourly_res_elec_2021-11-05.csv:  Hourly results for the buildings primarily using electric heating

Unfortunately, I didn't have the time to combine the gas and electric results into one set of files so you will have to do that yourself.  When you do combine them you will be able to determine which are gas heated and which are electrically heated via the output.xlsx file.  Column U titled ':primary_heating_fuel' will list the primary heating fuel for a datapoint on a given row (it should be either 'Electricity' or 'NaturalGas').  The solar panel issue should be resolved and a quick review of the results show that some buildings have negative 'net_site_eui_gj_per_m_sq' results.  Some of the column letters may have changed from those in past output.xlsx files but the titles should be the same.

**Comment by maybuksho** [comment]
@ckirney  thanks for sending the new dataset. I will work with it and update everyone on the progress during our next meeting.

**Comment by maybuksho** [comment]
@ckirney  please I need verification for the calculation of  'net_site_eui_gj_per_m_sq'

Currently, from the net_site_eui_gj_per_m_sq

**Comment by maybuksho** [comment]
The dataset have ben sent by Chris
